nerdberries/about/urls.py
from django.urls import path

from about.views import AboutAuthorView


app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
]

nerdberries/nerdberries/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('secret/', include('secret.urls', namespace='secret_func')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

nerdberries/posts/urls.py
from django.urls import path, re_path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.category_posts, name='category_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    re_path(r'^get_image/(?P<filename>.+)/$', views.get_image, name='get_image'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/make_purchase/',
        views.make_purchase, 
        name='make_purchase',
    ),
    path(
        'posts/<int:post_id>/return_purchase/',
        views.return_purchase, 
        name='return_purchase',
    ),
    path(
        'purchases/',
        views.purchases,
        name='purchases',
    ),
]

nerdberries/templates/includes/footer.html
    <p>© {{ year }} Copyright <span style="color:red">Nerd</span>Berries</p>    
    

nerdberries/templates/includes/form.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

<form method="post"
{% if action_url %}
  action="{% url action_url %}"
{% endif %}
>
{% csrf_token %}
{% for field in form %}
  <div class="form-category row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

nerdberries/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: gold">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><img 
      src="{% static 'img/logo.png' %}" 
      width="30" 
      height="30" 
      class="d-inline-block align-top" 
      alt=""><span
      style="color:red"> Nerd</span>Berries</a>
    {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'secret_func:ping_site' %} active {% endif %}"
          href="{% url 'secret_func:ping_site' %}">Секретная функция</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'posts:author' %} active {% endif %}"
          href="{% url 'about:author' %}">Рандомайзер</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'posts:purchases' %} active {% endif %}" 
          href="{% url 'posts:purchases' %}">Заказы</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'posts:post_create' %} active {% endif %}"
            href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:password_change' %} active {% endif %}" 
            href="{% url 'users:password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:logout' %} active {% endif %}"
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:login' %} active {% endif %}"
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light {% if view_name == 'users:signup' %} active {% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
  </div>
</nav>      