nerdberries/about/urls.py
from django.urls import path

from about.views import AboutAuthorView


app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
]

nerdberries/nerdberries/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('secret/', include('secret.urls', namespace='secret_func')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

nerdberries/posts/urls.py
from django.urls import path, re_path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.category_posts, name='category_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    re_path(r'^get_image/(?P<filename>.+)/$', views.get_image, name='get_image'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/make_purchase/',
        views.make_purchase, 
        name='make_purchase',
    ),
    path(
        'posts/<int:post_id>/return_purchase/',
        views.return_purchase, 
        name='return_purchase',
    ),
    path(
        'purchases/',
        views.purchases,
        name='purchases',
    ),
]

nerdberries/posts/models.py
from enum import unique
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel


User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    title = models.CharField(
        'Название',
        help_text='Введите название скрипта',
        max_length=200,
        unique=True,
    )
    text = models.TextField(
        'Описание скрипта',
        help_text='Введите описание скрипта'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Категория',
        help_text='Категория, к которой будет относится товар'
    )
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        verbose_name='Цена',
        help_text='Введите цену'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]
    
class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='Покупатель'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='purchases',
        verbose_name='Пост'
    )
    price = models.DecimalField(
        max_digits=10, 
        decimal_places=2,
        verbose_name='Цена',
        help_text='Введите цену'
    )
    date = models.DateTimeField(
        'Дата покупки',
        auto_now_add=True
    )
    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = 'Покупки'
        ordering = ['-date']


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )


class Follow(models.Model):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        blank=True,
        null=True
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Избранный автор',
        blank=True,
        null=True
    )

nerdberries/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import Textarea

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'category', 'price', 'image']
        widgets = {
            'text': Textarea(
                attrs={
                    'cols': 40,
                    'rows': 10,
                    'class': 'form-control',
                    'required id': 'id_text',
                }
            ),
        }

    def clean_text(self):
        data = self.cleaned_data['text']
        if not data:
            raise ValidationError('Заполните пожалуйста это поле')
        return data


class SearchForm(forms.Form):
    query = forms.CharField(
        label='Поиск', 
        max_length=100,
        required=False,
    )

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': Textarea(
                attrs={
                    'cols': 40,
                    'rows': 10,
                    'class': 'form-control',
                    'required id': 'id_text',
                }
            ),
        }

nerdberries/posts/views.py
import os

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.db import connection
from django.http import QueryDict, HttpResponse
from django.conf import settings

from core.paginator import paginator
from posts.forms import CommentForm, PostForm, SearchForm
from posts.models import Category, Post, Comment, Follow, Purchase


User = get_user_model()


def index(request):
    form = SearchForm(request.GET)
    posts = Post.objects.all()
    template = 'posts/index.html'
    context = {}

    if form.is_valid():
        query = form.cleaned_data.get('query')
        if query:
            sql_query = f"SELECT * FROM posts_post WHERE title LIKE '%{query}%' OR text LIKE '%{query}%'"
            with connection.cursor() as cursor:
                cursor.execute(sql_query)
                columns = [col[0] for col in cursor.description]
                posts = [dict(zip(columns, row)) for row in cursor.fetchall()]

            context.update({'query': query, 'posts': posts})

    page_number = request.GET.get('page')
    page_obj = paginator(posts, page_number, 10)

    query_dict = QueryDict(mutable=True)
    query_dict.update(request.GET)
    query_dict.pop('page', None)

    context.update({
        'page_obj': page_obj,
        'form': form, 
        'pagination_query_params': query_dict.urlencode(),
    })

    return render(request, template, context)


def category_posts(request, slug):
    template = 'posts/category_list.html'
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.all()
    page_number = request.GET.get('page')
    context = {
        'category': category,
        'page_obj': paginator(posts, page_number),
    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    page_number = request.GET.get('page')
    template = 'posts/profile.html'
    following = False
    if request.user.is_authenticated:
        if Follow.objects.filter(author=user, user=request.user).exists():
            following = True


    context = {
        'following': following,
        'author': user,
        'page_obj': paginator(posts, page_number),
    }
    return render(request, template, context)

def get_image(request, filename):
    image_path = os.path.join(settings.MEDIA_ROOT, filename)
    try:
        with open(image_path, 'rb') as image_file:
            image_data = image_file.read()
            return HttpResponse(image_data, content_type='image/jpeg')
    except FileNotFoundError:
        return HttpResponse(status=404)


def post_detail(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id)
    posts_count = post.author.posts.count
    comment_form = CommentForm()
    post_comments = Comment.objects.filter(post=post_id)
    template = 'posts/post_detail.html'
    product_purchased = False

    if request.user.is_authenticated:
        if Purchase.objects.filter(
            user=user, 
            post=post,
        ).exists():
            product_purchased = True

    context = {
        'form': comment_form,
        'comments': post_comments,
        'posts_count': posts_count,
        'post': post,
        'product_purchased': product_purchased,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    from_user = request.GET.get('from_user')

    if from_user:
        from_user = post.author

    if not post.author == from_user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    form = PostForm(instance=post)
    context = {'form': form, 'is_edit': True, 'post': post}
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):

    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    page_number = request.GET.get('page')
    context = {
        'page_obj': paginator(posts, page_number),
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(
            user=user,
            author=author
        )
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(author=author, user=request.user).exists():
        Follow.objects.get(user=request.user, author=author).delete()

    return redirect('posts:profile', username)

@login_required
def make_purchase(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id)
    Purchase.objects.get_or_create(
        user=user,
        post=post,
        price=post.price,
    )
    return redirect('posts:post_detail', post_id)

@login_required
def return_purchase(request, post_id):
    user = request.user
    post = get_object_or_404(Post, id=post_id)
    if Purchase.objects.filter(post=post, user=user).exists():
        Purchase.objects.get(post=post, user=user).delete()

    return redirect('posts:post_detail', post_id)

@login_required
def purchases(request):
    user = request.user
    purchases = user.purchases.all()
    page_number = request.GET.get('page')
    status_param = request.GET.get('status')

    page_obj = paginator(purchases, page_number, 10)
    template = 'posts/purchases.html'
    context = {
        'page_obj': page_obj,
        'status_param': status_param,
    }
    return render(request, template, context)

nerdberries/templates/posts/category_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Записи сообщества: {{ category.title }} {% endblock %}
{% block content %}
  <div class="container py-5"> 
    <h1>
      {{ category.title }}
    </h1>
    <p>
      {{ category.description }}
    </p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html'%}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div> 
  <div class="row justify-content-center">
    <div class="col-md-4 p-4">
      {% include 'posts/includes/paginator.html' %}
    </div> 
  </div> 
{% endblock %}

nerdberries/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} 
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %} 
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Добавить запись
            {% endif %}          
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data"
            {% if is_edit %}
            action="{% url 'posts:post_edit' post.id %}"
            {% else %}
            action="{% url 'posts:post_create' %}"
            {% endif %}
            >
              {% csrf_token %}
              {% for field in form %}
                <div class="form-category row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
              {% endfor %}
                </div>
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                  </button>
                </div>
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

nerdberries/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %} 
  {% if lets_following %}
    Давайте начнём!
  {% else %}
    Посты избранных авторов
  {% endif %} 
{% endblock %}

{% block content %}
  {% if lets_following %}
    <div class="container py-5"> 
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Вы ещё не подписались ни на одного автора!
            </div>
            <div class="card-body">
              <p>Давайте это исправим!</p>
              <a class="btn btn-primary" href="{% url 'posts:index' %}">
                Посмотреть последние обновления на сайте
              </a>
            </div> 
          </div> 
        </div>
      </div> 
    </div>
  {% else %}
    {% include 'posts/includes/switcher.html' %}
      <div class="container py-5">     
        <h1>Последние обновления избранных авторов</h1>
        {% load cache %}
        {% cache 20 follow_page %}
          {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %} 
              {% if post.category %}   
                <a href="{% url 'posts:category_list' post.category.slug %}">все записи группы</a>
              {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        {% endcache %}
      </div>
      <div class="row justify-content-center">
        <div class="col-md-4 p-4">
          {% include 'posts/includes/paginator.html' %}
        </div> 
      </div> 
  {% endif %}
{% endblock %}

nerdberries/templates/posts/index.html
<!-- ваш_проект/posts/templates/posts/index.html -->
{% extends 'base.html' %}
{% load static %}
{% block title %} 
  Это главная страница проекта Nerdberries
{% endblock %}
{% load thumbnail %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <form method="get" action="{% url 'posts:index' %}">
      {{ form.as_p }}
      <button type="submit">Искать</button>
    </form>

    {% if query %}
      {% if page_obj %}
        <p>Результаты поиска для: {{ query }}</p>
        {% load cache %}
        {% cache 20 index_page %}
          {% for post in page_obj %}
            {% include 'posts/includes/post_list.html' %} 
              {# 
                На самом деле это слепая SQL-инъекция, 
                но для демонстрации мы будем выводить данные posts напрямую
              #}
              {{ post }}  
              {% if post.category %}   
                <a href="{% url 'posts:category_list' post.category.slug %}">все записи группы</a>
              {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
        {% endcache %}
      {% else %}
        <p>По вашему запросу "{{ query }}" ничего не найдено.</p>
      {% endif %}
    {% else %}
      {# Выводим все посты, если запроса нет #}
      {% load cache %}
      {% cache 20 index_page %}
        {% for post in page_obj %}
          {% include 'posts/includes/post_list.html' %} 
            {% if post.category %}   
              <a href="{% url 'posts:category_list' post.category.slug %}">все записи группы</a>
            {% endif %} 
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      {% endcache %}
    {% endif %}
  </div>
  <div class="row justify-content-center">
    <div class="col-md-4 p-4">
      {% if page_obj %}
        <nav aria-label="Page navigation">
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1&{{ pagination_query_params }}">first</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ pagination_query_params }}">previous</a>
              </li>
            {% endif %}
            <li class="page-item disabled">
              <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
            </li>
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ pagination_query_params }}">next</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ pagination_query_params }}">last</a>
              </li>
            {% endif %}
          </ul>
        </nav>
      {% endif %}
    </div> 
  </div> 
{% endblock %}

nerdberries/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post|truncatechars:30 }} {% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-category list-category-flush">
        <li class="list-category-item">
          Дата публикации: {{ post.created|date:"d E Y" }} 
        </li>
        {% if post.category %} 
          <li class="list-category-item">
            Группа: {{ post.category.title }}
            <a href="{% url 'posts:category_list' post.category.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-category-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-category-item d-flex justify-content-between align-items-center">
          Всего товаров автора: <span>{{ posts_count }}</span>
        </li>
        <li class="list-category-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все товары пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-4" src="{{ im.url }}">
      {% endthumbnail %}
      <p>Название: {{ post.title }}</p>
      <p>
        {{ post.text }}
      </p>
      <p>
        Цена: {{ post.price }}
      </p>
      {% if product_purchased %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:return_purchase' post.id %}" role="button"
        >
          Товар уже куплен
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:make_purchase' post.id %}" role="button"
        >
          Купить товар
        </a>
  {% endif %}
      {% if request.user == post.author %}
        <li class="list-category-item">
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id%}">
            Редактировать запись
          </a>
        </li>
      {% endif %}      
      {% include 'posts/includes/post_comment.html' %}
    </article>
  </div> 
{% endblock %}

nerdberries/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} Профайл пользователя {{ author.username }} {% endblock %}
{% block content %}
<div class="mb-5">
  <div class="container py-5">
    <img src="{% url 'posts:get_image' filename='user_12.jpg' %}" alt="User Image">
    <h1>Все посты пользователя {{ author.username }} </h1>
    <h3>Всего постов: {{ page_obj.paginator.count }} </h3>
    {% if request.user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
</div>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "200x200" crop="center" as im %}
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>    
        {% if post.category %}   
          <a href="{% url 'posts:category_list' post.category.slug %}">все записи группы</a>
        {% endif %} 
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
  </div>
  <div class="row justify-content-center">
    <div class="col-md-4 p-4">
      {% include 'posts/includes/paginator.html' %}
    </div> 
  </div> 
{% endblock %}

nerdberries/templates/posts/purchases.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 
  Ваши покупки
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1 class="mb-4">Ваши покупки</h1>

    {% if status_param %}
      <div class="alert alert-success" role="alert">
        Статус заказа: {{ status_param|safe }} - В обработке
      </div>
    {% endif %}

    <div class="row">
      {% for purchase in page_obj %}
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <img src="{% static 'path/to/your/image.jpg' %}" class="card-img-top" alt="{{ purchase.post.title }}">
            <div class="card-body">
              <h5 class="card-title">{{ purchase.post.title }}</h5>
              <p class="card-text">{{ purchase.post.text }}</p>
              <p class="card-text"><strong>Цена:</strong> {{ purchase.price }} руб.</p>
              <p class="card-text"><strong>Дата покупки:</strong> {{ purchase.date|date:"F d, Y H:i" }}</p>
              <a 
                class="btn btn-lg btn-primary" 
                href="?status={{ purchase.id }}" role="button"
              >
                {% if status_param and status_param == purchase.id %}
                  Статус заказа: {{ status_param }}
                {% else %}
                  Статус заказа
                {% endif %}
              </a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>

    {% if page_obj %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1">Первая</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            </li>
          {% endif %}
          <li class="page-item disabled">
            <span class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
          </li>
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </div>
{% endblock %}