nerdberries/about/urls.py
from django.urls import path

from about.views import AboutAuthorView


app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
]

nerdberries/nerdberries/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('secret/', include('secret.urls', namespace='secret_func')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

nerdberries/secret/urls.py
from django.urls import path

from . import views


app_name = 'secret'

urlpatterns = [
    path('ping_site/', views.ping_site, name='ping_site')
]

nerdberries/secret/models.py
from django.db import models

# Create your models here.

nerdberries/secret/forms.py
from django import forms

class PingForm(forms.Form):
    site_url = forms.CharField(label='URL сайта', required=True)

nerdberries/secret/views.py
from encodings import utf_8
import subprocess
from sys import stderr

from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from secret.forms import PingForm


@csrf_exempt
def ping_site(request):
    if request.method == 'POST':
        form = PingForm(request.POST)
        if form.is_valid():
            site_url = form.cleaned_data['site_url']
            command = f'ping {site_url}'
            try:
                result = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
                result = result.decode('utf-8', errors='replace')
                print(result)
            except subprocess.CalledProcessError as e:
                result = str(e)
        else:
            result = 'Форма содержит ошибки.'
    else:
        form = PingForm()
        result = None

    return render(request, 'secret/ping.html', {'form': form, 'result': result})

nerdberries/templates/secret/ping.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %} 
  Пинг
{% endblock %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4 text-center">Пинг</h2>
        <form method="post" action="{% url 'secret_func:ping_site' %}">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
              {{ field }}
              {% if field.errors %}
                <small class="text-danger">{{ field.errors }}</small>
              {% endif %}
            </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary btn-block mt-3">Пингнуть</button>
        </form>

        {% if result %}
          <div class="mt-4">
            <h4 class="text-center">Результат пинга:</h4>
            <pre>{{ result }}</pre>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}